### ISSUE TITLE
Unable to resolve service for type 'Microsoft.AspNet.Cors.Core.ICorsService' while attempting to activate 'Microsoft.AspNet.Cors.CorsMiddleware'.

### ISSUE THREAD

**Issue by eyalsk** [aspnet/CORS#30]
I'm trying to use the middleware but I'm getting the following exception.

```
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNet.Cors.Core.ICorsService' while attempting to activate 'Microsoft.AspNet.Cors.CorsMiddleware'.
   at Microsoft.Framework.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Framework.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.AspNet.Builder.UseMiddlewareExtensions.<>c__DisplayClass2_0.<UseMiddleware>b__0(RequestDelegate next)
   at Microsoft.AspNet.Builder.Internal.ApplicationBuilder.Build()
   at Microsoft.AspNet.Hosting.Internal.HostingEngine.Start()
   at Microsoft.AspNet.Hosting.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at Microsoft.Framework.ApplicationHost.Program.ExecuteMain(DefaultHost host, String applicationName, String[] args)
   at Microsoft.Framework.ApplicationHost.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at dnx.host.Bootstrapper.RunAsync(List`1 args, IRuntimeEnvironment env, FrameworkName targetFramework)
   at dnx.host.RuntimeBootstrapper.ExecuteAsync(String[] args, FrameworkName targetFramework)
   at dnx.host.RuntimeBootstrapper.Execute(String[] args, FrameworkName targetFramework)
```

Here is the code I'm using.
Note that I've tried multiple variations but nothing worked, I got the same exception.

```CSharp
    public class Startup
    {
        public void ConfigureServices(IServiceCollection services)
        {
            services.ConfigureCors(co => co.AddPolicy("AllowAll", cp => cp.AllowAnyOrigin()));
		}

        public void Configure(IApplicationBuilder app)
        {
			app.UseFileServer(new FileServerOptions()
			{
				EnableDefaultFiles = true,
				EnableDirectoryBrowsing = true
			});

			app.UseCors("AllowAll");
		}
    }
```

Finally here is the project file.

```json
{
	"webroot": "cdnroot",

	"dependencies": {
		"Microsoft.AspNet.Server.IIS": "1.0.0-beta6",
		"Microsoft.AspNet.Server.WebListener": "1.0.0-beta6",
		"Microsoft.AspNet.StaticFiles": "1.0.0-beta6",
		"Microsoft.AspNet.Cors": "1.0.0-beta6"
	},

	"commands": {
		"web": "Microsoft.AspNet.Hosting --config hosting.ini"
	},

	"frameworks": {
		"dnxcore50": { }
	},

	"publishExclude": [
		"node_modules",
		"bower_components",
		"**.xproj",
		"**.user",
		"**.vspscc"
	],
	"exclude": [
		"cdnroot",
		"node_modules",
		"bower_components"
	]
}
```

**Comment by rynowak** [comment]
You currently need a call to `services.AddCors()` in addition to `services.ConfigureCors(...)`. We're already planning on merging these two APIs to it's less redundant.
